test_dir = getFilenamePath (getSourceFileName())
fileIn (pathConfig.appendPath test_dir @"..\mxs_set.ms")


fn test_from_array = (

)


fn test_elements = (

)


fn test_set_elements = (

)


fn test_discard = (

)


fn test_clear = (

)


fn test_copy = (

)


fn test_difference = (

)


fn test_difference_update = (

)


fn test_intersection = (

)


fn test_intersection_update = (

)


fn test_isdisjoint = (

)


fn test_issubset = (

)


fn test_issuperset = (

)


fn test_pop = (

)


fn test_symmetric_difference = (

)


fn test_symmetric_difference_update = (

)


fn test_union = (

)


fn test_update = (

)


fn test_to_array = (

)


test_from_array()
test_elements()
test_set_elements()
test_discard()
test_clear()
test_copy()
test_difference()
test_difference_update()
test_intersection()
test_intersection_update()
test_isdisjoint()
test_issubset()
test_issuperset()
test_pop()
test_symmetric_difference()
test_symmetric_difference_update()
test_union()
test_update()


print "test_mxs_set finished."